apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacitycapstone
  labels:
    app: udacitycapstone
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacitycapstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
  template:
    metadata:
      labels:
        app: udacitycapstone
    spec:
      containers:
        - image: machdinho/udacitycapstone
          imagePullPolicy: Always
          name: udacitycapstone
          ports:
            - containerPort: 80

