apiVersion: v1
kind: Service
metadata:
  name: udacitycapstone
  labels:
    app: udacitycapstone
spec:
  type: LoadBalancer
  selector:
    app: udacitycapstone
  ports:
    - port: 80
      targetPort: 80
